update master with 3D toolbar
TomographicImaging/CILViewer pull request #347
Opened 2023-06-15 23:43 UTC by paskino

Takes from https://github.com/Dagonite/CILViewer/tree/viewer_toolbar into current master 

Tested with vtk9

supersedes #337

2023-06-17 11:08 UTC, paskino commented
Unit tests are missing...

2024-01-24 15:45 UTC, paskino commented
The `FormDialog` for Volume render settings still is missing:

- [ ] a way to manually change the slider position: swap the `QLabel` for a [`QDoubleSpinBox`](https://doc.qt.io/qt-6/qdoublespinbox.html#details) https://github.com/TomographicImaging/eqt/issues/125
- [ ] Monitor `sliderDown` in the connection to the signal [`valueChanged`](https://github.com/vais-ral/CILViewer/blob/9287248ccf12f2a8e1e549d9637770aca01ce2e0/Wrappers/Python/ccpi/viewer/ui/VolumeRenderSettingsDialog.py#L93-L111) in the slot otherwise the volume render gets triggered too often.
- [ ] Add a way to change the maximum opacity

2024-05-23 10:38 UTC, hrobarts commented
@lauramurgatroyd showed me how to use the tool bar and it worked really well for this shell dataset from https://doi.org/10.5281/zenodo.6983008
![current_render_0002](https://github.com/TomographicImaging/CILViewer/assets/77114597/f4946b42-2a69-4b7d-b869-d1d75dcb1cda)

2024-12-09 14:51 UTC, DanicaSTFC requested changes

2024-12-09 14:51 UTC, DanicaSTFC commented on Wrappers/Python/ccpi/viewer/CILViewer.py
> +        self._volume_render_pars = {
The dialogs in the toolbar did not inherit the dark theme correctly. Probably this is due to not setting the parent of the dialog.

2025-05-21 18:19 UTC, jcornall commented
#458 supersedes this PR as it contains many of the same changes - this PR can now be closed. 

The `toolbar3d` branch was merged into `toolbar3d-settings`, which will be merged into `master`. The new branch uses eqt version 2.0.0.

2025-05-21 18:19 UTC, closed without merging